services:
  backend:
    build: ./backend
    container_name: backend_service
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend/asset_dashboard
    container_name: frontend_service
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/asset_dashboard:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
